version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: blog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
    ports:
      - "3306:3306"
    networks:
      - blog-nw
    volumes:
      - mysql_data:/var/lib/mysql

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.5
    container_name: redpanda-1
    command:
      - redpanda
      - start
      - --advertise-kafka-addr=redpanda-1:9092
    ports:
      - "9092:9092"
      - "8081:8081" # Optional: Web UI für Redpanda Console
    networks:
      - blog-nw

  blog-backend:
    image: fanki/blog-backend:0.1
    container_name: blog-backend
    depends_on:
      - mysql
      - redpanda
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://blog-mysql:3306/blogdb
      QUARKUS_DATASOURCE_USERNAME: dbuser
      QUARKUS_DATASOURCE_PASSWORD: dbuser
      KAFKA_BOOTSTRAP_SERVERS: redpanda-1:9092
    ports:
      - "9090:9090"
    networks:
      - blog-nw

  blog-validator:
    image: fanki/blog-validator:0.1
    container_name: blog-validator
    depends_on:
      - redpanda
    environment:
      KAFKA_BOOTSTRAP_SERVERS: redpanda-1:9092
    ports:
      - "8082:8082"
    networks:
      - blog-nw

networks:
  blog-nw:

volumes:
  mysql_data:
